replicaCount: 1

image:
  repository: juicedata/mount
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "ce-v1.1.0"

port: 9000
metricsPort: 9567
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 5000m
    memory: 5Gi
  requests:
    cpu: 1000m
    memory: 1Gi

hostNetwork: false
nodeSelector: {}
tolerations: []
affinity: {}

secret:
  # The JuiceFS file system name.
  name: ""
  # Connection URL for metadata engine (e.g. Redis)
  # Ref: https://juicefs.com/docs/community/databases_for_metadata
  metaurl: ""
  # Object storage type, such as `s3`, `gs`, `oss`
  # Ref: https://juicefs.com/docs/community/how_to_setup_object_storage
  storage: ""
  # Access key for object storage
  accessKey: ""
  # Secret key for object storage
  secretKey: ""
  # Bucket URL
  # Ref: https://juicefs.com/docs/community/how_to_setup_object_storage
  bucket: ""

# JuiceFS format options. Separated by spaces
# Example: "--inodes=1000000 --block-size=4M"
# Ref: https://juicefs.com/docs/community/command_reference#juicefs-format
formatOptions: ""

# Gateway Options. Separated by spaces
# Example: "--get-timeout=60 --put-timeout=60"
# Ref: https://juicefs.com/docs/community/command_reference#juicefs-gateway
options: ""
